import { Injectable } from '@angular/core';
import { Product } from '../model/product';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  productList: Product[] =  [
    {
    id: 1,
    catId: 1,
    author: 'Balázs Ágnes',
    title: 'Lufi és a hajmeresztő szerelem',
    description: 'Lufi és régi barátja, Szamóca kapcsolata új irányokat vesz. "Amikor véletlenül összefutok Szamócával, és ő rám emeli a kedves vadgesztenye szemét, akkor én egy jókora ütést érzek a mellkasomban, amitől néhány percre teljesen megbénulok, jéghideg lesz a tenyerem, és fülig vörösödöm..." - vallja be Lufi. Mindez, annyira felzaklatja, hogy például rövidre vágatja haját, amivel az egész osztály előtt nevetségessé válik. Azonban nemcsak ő, hanem körülötte szinte mindenkit utolér a szerelem, így például Pierre-t, a szomszéd francia fiút, a mindig csinos Gombos Zsuzsit, a gimi rocksztárját Bitász Ferit, a kényeskedő Pál Laurát sőt még Szamócát is. Hogy mi lesz mindebből, az kiderül a sorozat negyedik részéből.',
    image: 'src/assets/covers/8307105_5.jpg',
    price: 2999,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 2,
    catId: 1,
    author: 'Lucy Strange',
    title: 'A nővérek átka',
    description: 'Küzdelmes az élet Willa, Grace, Freya és három húguk számára. A hat, anya nélkül maradt lány egy tanyán él és dolgozik rettegett apjuk és egy átok árnyékában. Mikor megérkezik a vidékre a titokzatos Telihold vásár, a legidősebb lány, Grace végre egy kis vidámságot csempészhet az életébe, ám másnap, mikor a mutatványosok tovább vándorolnak, neki is nyoma vész. Willa utánaered, az Elveszett mocsáron át követve nyomait, ahol sűrű árnyak gyülekeznek. Ha sikerül közöttük átvergődnie, és egyesíteni családját, talán az apja által rejtegetett titkokra is fény derül, és szembenézhet legmélyebb félelmeivel... Lucy Strange legendákat és mágiákat ötvöző kalandregénye .',
    image: 'src/assets/covers/8283952_5.jpg',
    price: 2990,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 3,
    catId: 1,
    author: 'Szabó Tibor Bemjámin',
    title: 'EPIC 1 - Az első küldetés',
    description: 'Hat diák közös tanulócsoportba kerül a Rudiban, azaz a Különleges Tehetségek Ernest Rutherford Intézetében. Sádi, Röfi, Márkó, János, Zuzu és Alma Peti, vagyis a B Team tagjai kezdetben idegenek egymás számára. Ez az iskola tényleg az életre készíti fel őket, bár arról még sejtésük sincs, hogy ez pontosan mit is fog jelenteni. Az órákon olyan módszereket használnak a fiatalok nevelésére és képzésére, amelyeknek a törvényessége is kétséges, ráadásul a tanulócsoport a tanév indulása után nem sokkal óriási kalamajkába keveredik. Fogalmuk sincs, hová tart a történetük, de azt ösztönösen megérzik, hogy a slamasztikából csak összefogva, egymásban megbízva, egyszersmind a felnőttek világával szembefordulva tudnak kimászni.',
    image: 'src/assets/covers/8291981_5.jpg',
    price: 3490,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 4,
    catId: 1,
    author: 'J. K. Rowling',
    title: 'Az Ickabog',
    description: 'Duskáldia egykor a világ legboldogabb országa volt. Bővelkedett aranyban, egy pompázatos bajszú király uralkodott rajta, és olyan fenséges kolbászok, sajtok és sütemények készültek városaiban, hogy aki csak megkóstolta őket, táncra perdült örömében! Birodalomszerte minden szép és jó volt, kivéve a ködös északi részt, Lápföldét, ahol egy régi rege szerint a szörnyűséges Ickabog tanyázott. Minden épeszű ember tudta, hogy az Ickabog csak legenda, rossz gyerekek ijesztgetésére való. De a legendáknak megvan az a furcsa tulajdonságuk, hogy néha önálló életre kelnek...',
    image: 'src/assets/covers/8278801_5.jpg',
    price: 4790,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 5,
    catId: 1,
    author: 'Simon Farnaby',
    title: 'Haramia a szekrényemben',
    description: 'A Varázsló a sufnimban folytatása! Vanheldon, a vandálok királya nem lát a pipától, amióta Merdyn kővé változtatta a seregét. Bosszúvágyában ördögi tervet eszel ki: elrabolja Rose-t, visszaviszi a középkorba, és csaliként használja a varázslónak állított csapdában. De a lánya, akit a jövőbe küld, véletlenül Rose bátyját, Krist dugja a zsákjába. Uppsz!',
    image: 'src/assets/covers/8216019_5.jpg',
    price: 3499,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 6,
    catId: 1,
    author: 'Erna Sassen',
    title: 'Egy indián, mint te meg én',
    description: 'Boaz szereti a nagymamáját, szereti a csendet, és nagyon szeret olvasni, főleg az indiánokról. Az osztályban viszont egy barátja sincs, míg meg nem érkezik Aisha. A gyönyörű, hosszú fekete hajú Aisha, aki nem tud hollandul, de igazi indián, és rögtön Boaz mellé ül. Végre neki is van legjobb barátja!',
    image: 'src/assets/covers/7037715_5.jpg',
    price: 3490,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 7,
    catId: 1,
    author: 'Ecsédi Orsolya',
    title: 'Meleg a helyzet!',
    description: 'Goni egy totál rossz ördögkölyök, aki képtelen leszokni a jóságról. Rémálom tud lenni az élete, mert folyton elbukik a gonoszságban. Vajon lesz belőle vérbeli pokolfajzat?',
    image: 'src/assets/covers/6976086_5.jpg',
    price: 2699,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 8,
    catId: 1,
    author: 'Nancy Springer',
    title: 'Enola Holmes - A balkezes kisasszony esete',
    description: 'Enola Holmesnak egymagában kell boldogulnia a világ legnagyobb, legmocs-kosabb és legveszélyesebb városában, miközben a világ leghíresebb nyomozója - történetesen a bátyja -, Sherlock Holmes vadászik rá. Szabadsága érdekében menekülnie kell a családja elől, de hol találhat társakra?',
    image: 'src/assets/covers/6711543_5.jpg',
    price: 2999,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 9,
    catId: 1,
    author: 'Astrid Lindgren',
    title: 'Juharfalvi Emil újabb csínytevései',
    description: 'Juharfalvi Emilt mindenki ismeri Délföldön. A juharfalviak egy egész bársonyzacskóra való pénzt gyűjtenek össze, hogy a Macskaháj-tanya lakói Amerikába küldjék a kis pernahajdert. Ám Emil édesanyja váltig állítja, hogy Emil aranyos fiúcska. Pedig ő aztán tudhatná, hogy mennyi csibészségre képes, hiszen hűségesen lejegyzi valamennyi csínyt. Astrid Lindgren pedig kiváló érzékkel válogat közülük. Emil ebben a kötetben sem tétlenkedik: kisebb balesetet okoz egy egérfogóval, aztán apa fejére varázsolja a vérgombóclevest és a lángostésztát. A szélesréti vásáron jókora kalamajkát okoz két gólyalábbal meg egy frissen patkolóval.',
    image: 'src/assets/covers/871389_5.jpg',
    price: 2990,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 10,
    catId: 1,
    author: 'Jeff Kinney',
    title: 'Egy ropi naplója 4. - Kutya egy idő',
    description: 'Itt a nyári szünet - hétágra süt a nap, és minden kissrác a szabad levegőn rohangál. De hol van Greg Heffley? A házban gubbaszt, és videojátékokat játszik behúzott függöny mellett. Greg, aki saját bevallása szerint is benti éghajlathoz szokott, a leghőbb nyári vágyai szerint él: nincsenek kötöttségek és nincsenek szabályok. De Greg anyukájának más az elképzelése az ideális nyárról - olyan, ami dugig van kinti játékokkal és "családi együttlétekkel". Kinek az akarata jut majd érvényre? Vagy esetleg a Heffley-család új tagja mindent a feje tetejére állít?',
    image: 'src/assets/covers/829757_5.jpg',
    price: 2999,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 11,
    catId: 1,
    author: 'Bessenyei Gábor',
    title: 'Tested és lelkem',
    description: 'Hogyan is lenne? Igazából nincs is annál jobb, mint eljutni oda a lánnyal, hogy meztelenül láthasd. De mi van akkor, ha nemcsak te láthatod? Hanem az összes haverod, az egész iskola, és hirtelen mindenki azt hiszi, hogy jár neki belőle egy darab. Ez nem lehet a valóság. Mert ha az, nem biztos, hogy el bírom viselni. De ha én nem bírom elviselni, mi lesz Lucával?',
    image: 'src/assets/covers/8147390_5.jpg',
    price: 3899,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 12,
    catId: 1,
    author: 'Zágoni Balázs',
    title: 'Karácsonyi kitérő',
    description: 'Anya, Apa és a három gyerek már előre retteg advent időszakától, mert jól emlékeznek a tavalyi karácsonyra. Akkor semmivel sem készültek el időben, a vendégek túl korán érkeztek, ráadásul egy tepsi isler is odaégett. De idén minden másképp lesz, dönti el a tízéves Emma, és egy darabig valóban úgy tűnik, hogy - a gondos szervezésnek hála - idén békés és boldog lesz az ünnep. Ám egy zebránál kéregető, jó szándékú koldus minden tervet felborít, és még kétségbe ejtőbbé válik a helyzet, mint tavaly. Lehet még szép a karácsonyuk? Vajon ott keresik a karácsony szentségét, ahol kell és érdemes?',
    image: 'src/assets/covers/7935525_5.jpg',
    price: 2490,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 13,
    catId: 1,
    author: 'Nina Kenwood',
    title: 'Fejben jobban hangzott',
    description: 'Tényleg senkit nem érdeklek? Nem érek annyit, mint mások? Mindenki a pattanásaimat nézi? Csak én érzem furának a testem, vagy más is annak látja? A többiek vajon miről beszélgetnek? Hogy néz ki belülről egy kapcsolat? Lesz-e valaha, aki olyannak fogad el és szeret, amilyen vagyok?" - ilyen kérdések kavarognak a tizenöt éves Natalie fejében, aki tényleg úgy érzi, hogy az élete romokban hever. Ráadásul a "normális" kamaszokkal ellentétben nem szeret bulizni, inni, zavarban van ismeretlenek társaságában, és még soha senkivel nem csókolózott. Aztán felbukkan az egyik legjobb barátja bátyja, Alex, aki valamiért nem akar lekopni Natalie-ról. A köztük lévő kapcsolat azonban nem egy szokásos love story lesz, hanem sokkal több: Natalie végre megtanulja, hogy bátran önmaga lehet.',
    image: 'src/assets/covers/7926319_5.jpg',
    price: 2999,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 14,
    catId: 1,
    author: 'Laura Ellen Anderson',
    title: 'Vámpyr Vilma és az emléktolvaj',
    description: 'Elérkezett Vámpyr Vilma hatalmas szülinapi bulijának éjjele, ő pedig BORZASZTÓAN izgatott. Ám Noktürnia teremtményei különösen viselkednek, mintha egyikük sem emlékezne semmire - még Vilma szülinapi bulijára sem!',
    image: 'src/assets/covers/7925996_5.jpg',
    price: 2490,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 15,
    catId: 1,
    author: 'Julia Dippel',
    title: 'Izara - Csendes víz',
    description: 'Immár minden halhatatlan tud Izaráról. Mialatt apja a Phalanx tömlöcében tölti megérdemelt büntetését, a Liga beidézi Arit. Kénytelen kétes megállapodásokat kötni annak érdekében, hogy a katakombák fővárosában ő életben, a Luciannal való tiltott köteléke pedig titokban maradjon. Ám nem csupán a Nagytanács elé kell állnia, hanem a boszorkányokkal és Lucian családjával is szembe kell néznie... Egyre jobban belegabalyodik a hazugságok, vádak és kétségek hálójába. Átláthatatlan, hogy ebben a zűrzavarban ki mozgatja a szálakat, ezért Arinak nemcsak saját életét kell féltenie, hanem szerelméét is.',
    image: 'src/assets/covers/7906411_5.jpg',
    price: 4699,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 16,
    catId: 1,
    author: 'Louisa May Alcott',
    title: 'Jo fiai',
    description: 'Louisa May Alcott családregényének, a Kisasszonyoknak befejező része a felnőtté válás nehézségeiről, csábításokról, tévutakról és tapasztalatokról egyaránt szól. Hála az öreg Mr. Laurence örökségének, tíz évvel az alapítás után továbbra is fogadja a diákokat és Jo Bhaer kísérleti iskolája főiskolává növi ki magát. A régi növendékek ifjakká, illetve bájos és céltudatos fiatal hölgyekké serdültek, akik a maguk útját járják a nagyvilágban. Ám egy fiatalnak ugyanannyi gondja akad, mint egy gyereknek, az élet komoly akadályokat gördít a fiatalok elé, akik mind ezek ellenére maradnak, akik mindig is voltak, Jo March fiai.',
    image: 'src/assets/covers/7889263_5.jpg',
    price: 2990,
    stock: 0,
    featured: false,
    active: true,
   },
  {
    id: 17,
    catId: 1,
    author: 'Liz Kessler',
    title: 'Emily Windsnap és a kastély a ködben',
    description: 'A mágikus gyűrű, amit a félig sellő, félig hétköznapi lány, Emily Windsnap, a homokban talál, Neptunusz tulajdona, aki vissza akarja azt kapni. De miután a kislány felveszi a gyűrűt, az nem jön le többé az ujjáról, és a tengerek dühös istene vihart bocsát Emily hajójára, aki társaival együtt kisodródik a nyílt tengerre. Amikor a bárka megállapodik, Emily és legjobb barátnője, Shona egy rejtélyes kastélyt pillantanak meg a látóhatáron, ködbe burkolózva...',
    image: 'src/assets/covers/7889042_5.jpg',
    price: 2490,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 18,
    catId: 1,
    author: 'Sara Pennypacker',
    title: 'Klementin és a családi kupaktanács',
    description: 'Klementin az idegösszeomlás szélén áll. A szülei kitették otthon a "Családi kupaktanács!" táblát, és ő attól tart, hogy valamit megint elrontott. Túl sokat piszkálta a kisöccsét? Szanaszét hagyta a dolgait? Vagy esetleg túl sok egészségtelen ételt evett? Akárhogy is próbálkozik Klementin, szülei nem hajlandóak elárulni, mi a kupaktanács témája. Ha rajta múlna, az szerepelne a napirendi pontok között, hogy "Gorilla beszerzése itthonra". Ehelyett azonban valami teljesen másról van szó. És a más nem mindig jelent ám jót!',
    image: 'src/assets/covers/7615504_5.jpg',
    price: 2599,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 19,
    catId: 1,
    author: 'Jennifer Chambliss Bertman',
    title: 'Könyvvadászok',
    description: 'Emily bohém szüleinek mániája, hogy minden évben új helyre költöznek. Most éppen San Francisco következik, ami legalább jó hír, hiszen itt van a Könyvvadászat központja. Emily lelkes könyvvadász: a játék lényege, hogy bárki bárhol elrejthet egy könyvet, a megtaláló pedig egy online rendszer alapján pontokat kap.',
    image: 'src/assets/covers/5211701_5.jpg',
    price: 3790,
    stock: 10,
    featured: false,
    active: true,
   },
  {
    id: 20,
    catId: 1,
    author: 'Leiner Laura',
    title: 'Állj mellém',
    description: 'A végéhez közeledik az Iskolák Országos Versenye, a négy kitaszított szirteses diák pedig rendületlenül menetel a döntő felé. Sára, Vivi, Rajmund és Dominik határozott céllal érkeztek a versenyre: meg akarják nyerni a kupát, ezzel bizonyítva, hogy ők többek, mint néhány múltbéli hiba.',
    image: 'src/assets/covers/8014953_5.jpg',
    price: 3690,
    stock: 10,
    featured: false,
    active: true,
   }
  ]




  constructor() { }

  getAll(): Product[] {
    return this.productList;
  }
}
